### ISSUE TITLE
fix config for windows build

### ISSUE THREAD

**Issue by maurizioandreotti** [maurizioandreotti/D-Rats#17]
in particular compare it with distXP.bat to remove xcopy lines

**Comment by yo2loj** [comment]
Add
xcopy libexec\LZHUF_1.EXE .\dist\libexec /s /d /y /f /i'
after 
xcopy  ui     .\dist\ui /s /d /y /f /i

**Comment by yo2loj** [comment]
Modified the config.py to skip unneeded DLLs for the windows build

**Comment by yo2loj** [comment]
Works fine on Win7

**Comment by maurizioandreotti** [comment]
works also on XP

**Comment by yo2loj** [comment]
I also updated the libexe content...
- lzhuf now returns an errocode if there's a compress/decompress error
- added a makefile for the windows version
- updated the windows binary from the new source code
I think this should close the LZHUF topic once and forever :-)
