### ISSUE TITLE
recover code from latest beta from Dan.... 

### ISSUE THREAD

**Issue by maurizioandreotti** [maurizioandreotti/D-Rats#23]
As i just bumped into a sligtly updated version  by Dan with respect to th 0.3.3 which was the starting point here......

Changes to D-RATS since version 0.3.3.
Python 2.5's py2exe doesn't need gio.
New-fangled MacOS .app with D-RATS icon.
Set proper permissions on installer build and cleanup build directory.
Include gio module in py2exe build.
Patch from Steve to check more paths in platform.py when determining where we're installed.
Add a function to get a field caption.
Allow designating QSTs as going to all ports, or just the current port.
Allow expiring stations from the heard list after n minutes.
Increase the shutdown delay when an offline message is configured giving time for the final message to go out.
Fix threaded QSTs (like weather, RSS, etc).
Update copyright dates...and add python version to the about box.
Fix typo causing the date column to sort with the size column in Files.
Support for sending attachments via WL2K.
Support for receiving file attachements from WL2K.
Enable OSX menubar integration (runtime R10 required).
Fix up finding the source directory in MacOSPlatform, for the structure of the new-fangled .app.
Disable the lookup-by-address function since it was rendered useless by Yahoo discontinuing their geocoding service.
Disable automatic global key handler on MacOS so that we can have our 'c' key back :)
Add an uninstaller to the D-RATS win32 build and register it with the Add/Remove programs tool.
Fix inverted speed/course in GPS-A transmission.
Fixes for GPS-A transmission (lots of 'em).
Fix transmitting GPS-A beacons with less than 10 degrees latitude.
Fix displaying GPS-A icons properly.
Download the latest daily build from:
http://dev.d-rats.com/drats_daily/daily-02232012/

**Comment by yo2loj** [comment]
Nice!
