### ISSUE TITLE
APRS export

### ISSUE THREAD

**Issue by maurizioandreotti** [maurizioandreotti/D-Rats#62]
? creare un convertitore di coordinate interfacciato con D-RATS che, quando quest'ultimo riceve le coordinate, le invia (tramite localhost e porta interna 14550) a DPRSInterface col formato standar APRS? DPRSInterface potrebbe così condividere (a discrezione utente) su APRS.fi l'avvenuta ricezione delle posizioni geografiche degli utenti D-RATS e contemporaneamente visualizzare le stesse su mappa locale Ui-View o APRSIS32...

**Comment by EA1AXY** [comment]
" What would be the simplest solution? For all this, being able to access that port 9500 from the D-Rats program without having to activate the D-Rats Repeater, can I do it? I do not know ..." my conclusion after testing D-Rats Repeater ...
