### ISSUE TITLE
QST Type Weather (WU) non-functional

### ISSUE THREAD

**Issue by dslotter** [maurizioandreotti/D-Rats#63]
The QST type Weather (WU) is using a web API for Weather Underground which has been decommissioned. This means that this functionality is broken.

The decommissioned API is described on [apicommunity.wunderground.com/weatherapi/topics/weather-underground-api-update](https://apicommunity.wunderground.com/weatherapi/topics/weather-underground-api-update)

Recommend switching to alternative provider, [OpenWeatherMap.org](https://www.openweathermap.org)

**Comment by maurizioandreotti** [comment]
will check, thanks

**Comment by maurizioandreotti** [comment]
flirst implementation done of current and 5 days forecast weather done - see upcoming 0.3.9 beta 1
